### ISSUE TITLE
Admin can remove Students/Teachers

### ISSUE THREAD

**Issue by ahzamm** [AhzamAhmed6/online_school#9]
- [x] Create DeleteStudent Link
- [ ] Create DeleteTeacher Link
- [ ] Move DeleteStudent Link inside ListOneStudent
- [ ] Move DeleteTeacher Link inside ListOneTeacher

**Comment by AhzamAhmed6** [comment]
Testing Message

**Comment by Usaid529** [comment]
create a milestone
